package parkingspot.gae.db;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.FetchOptions;
import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;
import com.google.appengine.api.datastore.Query;
import com.google.appengine.api.datastore.Transaction;
import com.google.appengine.api.datastore.Query.Filter;
import com.google.appengine.api.datastore.Query.FilterOperator;
import com.google.appengine.api.datastore.Query.FilterPredicate;

/**
 * GAE ENTITY UTIL CLASS: "User" <br>
 * PARENT: Campus <br>
 * KEY: A lot long Id generated by GAE <br>
 * FEATURES: <br>
 * - "name" a {@link String} with the name of the user (e.g. "First Last")<br>
 * - "loginID" a {@link String} with the login ID of the user (one of these, in this order: user id, email, external Open
 * - "email" a {@link String} with the email of the user (e.g. blank@email.com)<br> NYI
 * - "permit" a {@link String} with the type of permit owned (e.g. "A","B","C")<br>
 */

public class Users {
	
    //
    // SECURITY
    //
    
    /**
     * Private constructor to avoid instantiation.
     */
    private Users() {
    }
    
    //
    // KIND
    //
    
    /**
     * The name of the User ENTITY KIND used in GAE.
     */
    private static final String ENTITY_KIND = "User";
    
    /**
     * Return the Key for a given user id given as String. 
     * @param userId A string with the User ID (a long).
     * @return the Key for this userID. 
     */
    public static Key getKey(String userId) {
            long id = Long.parseLong(userId);
            Key userKey = KeyFactory.createKey(ENTITY_KIND, id);
            return userKey;
    }
    
    /**
     * Return the string ID corresponding to the key for the user.
     * @param user The GAE Entity storing the user.
     * @return A string with the lot ID (a long).
     */
    public static String getStringID(Entity user) {
            return Long.toString(user.getKey().getId());
    }
    
    //
    // NAME
    //
    
    /**
     * The property name for the <b>name</b> of the user profile.
     */
    private static final String NAME_PROPERTY = "name";
    
    /**
     * Return the name of the user. 
     * @param user The GAE Entity storing the user.
     * @return the name of the user. 
     */
    public static String getName(Entity user) {
	        Object name = user.getProperty(NAME_PROPERTY);
	        if (name == null) name = "";
	        return (String)name;
    }
    
    /**
     * The regular expression pattern for the name of the admin profile.
     */
    private static final Pattern NAME_PATTERN = Pattern.compile("\\A[A-Za-z]+([ -][A-Za-z]+){0,10}\\Z");
	
    /**
     * Check if the name is correct for a user. 
     * @param name The checked string. 
     * @return true is the name is correct. 
     */
    public static boolean checkName(String name) {
            Matcher matcher=NAME_PATTERN.matcher(name);
            return matcher.find();
    }
    
    //
    // LOGIN ID
    //
    
    /**
     *  The property name for the <b>loginID</b> of the admin profile.
     */
    private static final String LOGIN_ID_PROPERTY = "loginID";
    //LOGIN_ID_PROPERTY = email address tied to Google OAuth?
    
    /**
     * Return the login ID of the profile. 
     * @return a String with the permit type. 
     */
    public static String getLoginID(Entity user) {
            Object val=user.getProperty(LOGIN_ID_PROPERTY);
            if (val==null) return "";
            return (String) val;
    }
    
    //
    // Permit
    //
    
    /**
     *  The property name for the <b>permit</b> of the user.
     */
    private static String PERMIT_PROPERTY = "permit";
    
    /**
     * Return the permit type of the profile. 
     * @param campus The Entity storing the user profile.
     * @return a String with the login ID. 
     */
    public static String getPermit(Entity user) {
            Object val=user.getProperty(PERMIT_PROPERTY);
            if (val==null) return "";
            return (String) val;
    }
    
    //
    // CREATE USER
    //

    /**
     * Create a new user if the login ID is correct and none exists with this id.
     * @param loginID The id for this user.
     * @return the Entity created with this id or null if error
     */
    public static Entity createUser(String loginID) {
            Entity user = null;
            DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
            Transaction txn = datastore.beginTransaction();
            try {
            
                    user = getUserWithLoginID(loginID);
                    if (user!=null) {
                            return null;
                    }
                    
                    user = new Entity(ENTITY_KIND);
                    user.setProperty(LOGIN_ID_PROPERTY, loginID);
                    datastore.put(user);

                txn.commit();
            } finally {
                if (txn.isActive()) {
                    txn.rollback();
                }
            }
            
            return user;
    }
    
    //
    // GET USER
    //

    /**
     * Get the user based on a string containing its long ID.
     * 
     * @param id A {@link String} containing the ID key (a <code>long</code> number)
     * @return A GAE {@link Entity} for the User or <code>null</code> if none or error.
     */
    public static Entity getUser(String userId) {
            Entity user = null;
            try {
                    DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
                    long id = Long.parseLong(userId);
                    Key userKey = KeyFactory.createKey(ENTITY_KIND, id);
                    user = datastore.get(userKey);
            } catch (Exception e) {
                    // TODO log the error
            }
            return user;
    }
    
    /**
     * Get an user based on a string containing its loginID.
     * @param loginID The login of the user as a String.
     * @return A GAE {@link Entity} for the user or <code>null</code> if none or error.
     */
    public static Entity getUserWithLoginID(String loginID) {
            DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
            return getUserWithLoginID(datastore, loginID);
    }
    
    /**
     * Get a user based on a string containing its name.
     * @param datastore The current datastore instance. 
     * @param name The name of the user as a String.
     * @return A GAE {@link Entity} for the User or <code>null</code> if none or error.
     */
    public static Entity getUserWithLoginID(DatastoreService datastore, String loginID) {
            Entity user = null;
            try {
                    
                    Filter hasLoginID =
                                      new FilterPredicate(NAME_PROPERTY,
                                                          FilterOperator.EQUAL,
                                                          loginID);
                    Query query = new Query(ENTITY_KIND);
                    query.setFilter(hasLoginID);
                    List<Entity> result = datastore.prepare(query).asList(FetchOptions.Builder.withLimit(10));
                    if (result!=null && result.size()>0) {
                            user=result.get(0);
                    }
            } catch (Exception e) {
                    // TODO log the error
            }
            return user;
    }
    
    //
    // UPDATE USER
    //
    
    /**
     * Update the current description of the User.
     * @param userID A string with the user ID (a long).
     * @param name The name of the user as a String.
     * @param loginID The login ID of the user as a String.
     * @return true if succeed and false otherwise
     */
    public static boolean updateUserCommand(String userID, String name, String permit) {
            Entity user = null;
            try {
            		user = getUser(userID);
            		user.setProperty(NAME_PROPERTY, name);
            		user.setProperty(PERMIT_PROPERTY, permit);
                    DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
                    datastore.put(user);
            } catch (Exception e) {
                    return false;
            }
            return true;
    }
    
    //
    // DELETE USER
    //
    
    /**
     * Delete the user if not linked to anything else.
     * @param userID A string with the user ID (a long).
     * @return True if succeed, false otherwise.
     */
    public static boolean deleteUserCommand(String userID) {
            try {
                    DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
                    datastore.delete(getKey(userID));
            } catch (Exception e) {
                    return false;
            }
            return true;
    }
    
    //
    // QUERY USERS
    //
    
    /**
     * Return the requested number of users (e.g. 100).  
     * @param limit The number of users to be returned. 
     * @return A list of GAE {@link Entity entities}. 
     */
    public static List<Entity> getFirstUsers(int limit) {
            DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
            Query query = new Query(ENTITY_KIND);
            List<Entity> result = datastore.prepare(query).asList(FetchOptions.Builder.withLimit(limit));
            return result;
    } 
   
}
